platform :ios, '11.0'

target 'VacationPlanner' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for VacationPlanner
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'TextFieldEffects'
    pod 'IQKeyboardManager'
    
    target 'VacationPlannerTests' do
        inherit! :search_paths
        # Pods for testing
    end

    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
